---
title: "premix stability all included"
author: "Aguirre"
date: "`r Sys.Date()`"
output: html_document
params:
  df: !r NULL
  mark: !r NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df_format <- function(df){
  df_formatted <- melt(df)
  colnames(df_formatted) = c("id", "marker", "source", "day", "value" )
  df_formatted
}

markers_violin <- function(df, marker_name, title = "Violin Plot") {
  ## The dataframe df must have a patient column, a marker column, and as many columns as there are days evaluated
  ## patient   | marker | Day 1 | Day 2 | ... | Day n
  ## patient1  | CD57   | 36.65 | 42.67 | ... | value n
  df_formatted <- df_format(df)
  p <- ggplot(data = df_formatted, aes(x = day, y = value)) +
    geom_violin(trim = FALSE, alpha = 0.2, aes(fill = day), show.legend = FALSE) +
    geom_boxplot(alpha = 0.2, show.legend = FALSE, width = 0.3) +
    geom_line(linetype = "dashed", linewidth = .6, aes(group = id), color = "gray20") +
    geom_point(aes(shape = id), alpha = 1, size = 2) +
    xlab("Day") + 
    ylab(marker_name) +
    ggtitle(title) + 
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5))+
    scale_x_discrete(expand = expansion(add = 0.5))
  print(p)
}


for (tble in (test %>% group_split(Source))) { 
  title = paste0("Violin Plot for ", unique(tble$Marker), " (", unique(tble$Source), ")")
  markers_violin(tble, unique(tble$Marker), title = title)
} 
```

